### ISSUE TITLE
Use Github deployment instead of comment

### ISSUE THREAD

**Issue by ruiramos** [danburtenshaw/s3-website-pr-action#2]
Hey Dan, great work on putting this action together, I was doing something similar with a bunch of actions and bash scripts put together but this is much cleaner. 
An improvement I'd suggest would be to use [Github Deployments](https://developer.github.com/v3/repos/deployments/) to indicate success and expose the deployment URL instead of a comment on the PR. I'm currently using [this action](https://github.com/bobheadxi/deployments) for that.
Happy to help as well! Cheers.

**Comment by danburtenshaw** [comment]
Hey @ruiramos, 
Thanks for this great idea, I wasn't actually aware of the GitHub Deployments feature but this seems like a perfect use case for it. I have gone ahead and implemented this into [v2](https://github.com/marketplace/actions/s3-website-pr?version=v2.0.0). I'd really appreciate it if you could give it a try and let me know if you have any issues.

I have made this a major version bump as the PR Closed workflow will now need access to the GitHub token. This is added the same way as we do in the PR Created workflow: 
`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
